app:
  build: .
  env_file: .env
  expose:
    - "5000"
  links:
    - postgres
    - redis
  command: manage.py runserver_gunicorn

worker:
  build: .
  env_file: .env
  links:
    - redis
  command: worker.py

redis:
  image: redis:latest

postgres:
  restart: always
  image: postgres:latest
  volumes_from:
    - data
  ports:
    - "5432:5432"

data:
  restart: always
  image: busybox 
  volumes:
    - /var/lib/postgresql
  command: "true"
